version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      time: '13:00'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
